#!bin/sh

echo "Is it morning? Please answer yes or no"
read timeofday

if [ $timeofday = "yes" ]
then 
 echo "Good morning"
elif [ $timeofday = "no" ]
 echo "Good afternoon"
else
 echo "Good Sorry, $timeofday not recognized. Enter yes or no"
 exit1
fi

exit 0

